# Generated by Django 3.2.25 on 2025-03-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20250303_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
