# Generated by Django 3.2.25 on 2025-02-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20250228_1140'),
        ('blood', '0006_bloodrequest_request_by_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='patient_age',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_by_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
