# Generated by Django 3.2.25 on 2025-02-28 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20250301_0245'),
        ('blood', '0007_auto_20250301_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='urgency_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_by_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='hospital.hospital'),
        ),
    ]
