# Generated by Django 3.2.25 on 2025-03-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_bloodrequest_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
