# Generated by Django 3.2.25 on 2025-03-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20250301_0245'),
        ('donor', '0003_auto_20250228_0319'),
        ('blood', '0010_bloodrequest_is_emergency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_schedules', to='donor.donor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_schedules', to='hospital.hospital')),
            ],
        ),
    ]
