# Generated by Django 3.2.25 on 2025-03-03 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_id'),
        ('donor', '0005_auto_20250303_0931'),
        ('blood', '0011_donationschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='donor.donor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='patient.patient')),
            ],
        ),
    ]
