# Generated by Django 3.2.25 on 2025-02-28 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='blood_type',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='hospital',
            new_name='request_by_hospital',
        ),
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
