# Generated by Django 3.2.25 on 2025-02-28 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20250228_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='quantity',
            new_name='unit',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_by_hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='hospital.hospital'),
        ),
    ]
